cursos/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from . import views


urlpatterns = [
    path('estudiantes/', views.lista_estudiantes, name='lista_estudiantes'),
    path('estudiantes/agregar/', views.agregar_estudiante, name='agregar_estudiante'),
    path('estudiantes/editar/<int:estudiante_id>/', views.editar_estudiante, name='editar_estudiante'),
    path('estudiantes/eliminar/<int:estudiante_id>/', views.eliminar_estudiante, name='eliminar_estudiante'),

    path('profesores/', views.lista_profesores, name='lista_profesores'),
    path('profesores/agregar/', views.agregar_profesor, name='agregar_profesor'),
    path('profesores/editar/<int:profesor_id>/', views.editar_profesor, name='editar_profesor'),
    path('profesores/eliminar/<int:profesor_id>/', views.eliminar_profesor, name='eliminar_profesor'),

    path('cursos/', views.lista_cursos, name='lista_cursos'),
    path('cursos/agregar/', views.agregar_curso, name='agregar_curso'),
    path('cursos/editar/<int:curso_id>/', views.editar_curso, name='editar_curso'),
    path('cursos/eliminar/<int:curso_id>/', views.eliminar_curso, name='eliminar_curso'),

    path('lecciones/', views.lista_lecciones, name='lista_lecciones'),
    path('lecciones/agregar/', views.agregar_leccion, name='agregar_leccion'),
    path('lecciones/editar/<int:leccion_id>/', views.editar_leccion, name='editar_leccion'),
    path('lecciones/eliminar/<int:leccion_id>/', views.eliminar_leccion, name='eliminar_leccion'),

    path('', auth_views.LoginView.as_view(template_name='cursos/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('registro/', views.registrar_usuario, name='registro_usuario'),
    path('index/', views.index, name='index'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestor_cursos/urls.py
from django.contrib import admin
from django.urls import path, include  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cursos.urls')),  
]

cursos/models.py
from django.db import models
from django.contrib.auth.models import User

class Estudiante(models.Model):
    identificacion = models.CharField(primary_key=True, max_length=20)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)

class Profesor(models.Model):
    identificacion = models.CharField(primary_key=True, max_length=20)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)

class Curso(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    profesores = models.ManyToManyField(Profesor, related_name='cursos')
    estudiantes = models.ManyToManyField(Estudiante, related_name='cursos')
    
    def __str__(self):
        return self.nombre

class Leccion(models.Model):
    nombre = models.CharField(max_length=100)
    curso = models.ForeignKey(Curso, related_name='lecciones', on_delete=models.CASCADE)
    descripcion_actividad = models.TextField()
    contenido = models.FileField(upload_to='contenido_lecciones/')

class UserProfile(models.Model):
    USER_TYPE_CHOICES = (
        ('profesor', 'Profesor'),
        ('estudiante', 'Estudiante'),
        ('administrador', 'Administrador'),
    )
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES)

cursos/forms.py
from django import forms
from .models import Estudiante, Profesor, Curso, Leccion, UserProfile
from django.contrib.auth.models import User

class EstudianteForm(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = ['identificacion', 'nombre', 'apellido']
        widgets = {
            'identificacion': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
        }

class ProfesorForm(forms.ModelForm):
    class Meta:
        model = Profesor
        fields = ['identificacion', 'nombre', 'apellido']
        widgets = {
            'identificacion': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
        }

class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = ['nombre', 'descripcion', 'profesores', 'estudiantes']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'profesores': forms.SelectMultiple(attrs={'class': 'form-select'}),
            'estudiantes': forms.SelectMultiple(attrs={'class': 'form-select'}),
        }

class LeccionForm(forms.ModelForm):
    class Meta:
        model = Leccion
        fields = ['nombre', 'curso', 'descripcion_actividad', 'contenido']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'curso': forms.Select(attrs={'class': 'form-select'}),
            'descripcion_actividad': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'contenido': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

class CustomAuthenticationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password', 'email')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('user_type', )

cursos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Estudiante, Profesor, Curso, Leccion, UserProfile
from .forms import EstudianteForm, ProfesorForm, CursoForm, LeccionForm, UserForm, UserProfileForm
from django.contrib.auth.models import User

# Vistas Estudiantes --------------------------------------------------

def lista_estudiantes(request):
    estudiantes = Estudiante.objects.all()
    return render(request, 'cursos/lista_estudiantes.html', {'estudiantes': estudiantes})

def agregar_estudiante(request):
    if request.method == 'POST':
        form = EstudianteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_estudiantes')
    else:
        form = EstudianteForm()
    return render(request, 'cursos/agregar_estudiante.html', {'form': form})

def editar_estudiante(request, estudiante_id):
    estudiante = get_object_or_404(Estudiante, pk=estudiante_id)
    if request.method == 'POST':
        form = EstudianteForm(request.POST, instance=estudiante)
        if form.is_valid():
            form.save()
            return redirect('lista_estudiantes')
    else:
        form = EstudianteForm(instance=estudiante)
    return render(request, 'cursos/editar_estudiante.html', {'form': form, 'estudiante': estudiante})

def eliminar_estudiante(request, estudiante_id):
    estudiante = get_object_or_404(Estudiante, pk=estudiante_id)
    if request.method == 'POST':
        estudiante.delete()
        return redirect('lista_estudiantes')
    return render(request, 'cursos/eliminar_estudiante.html', {'estudiante': estudiante})

# Vistas Profesores -----------------------------------------------

def lista_profesores(request):
    profesores = Profesor.objects.all()
    return render(request, 'cursos/lista_profesores.html', {'profesores': profesores})

def agregar_profesor(request):
    if request.method == 'POST':
        form = ProfesorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_profesores')
    else:
        form = ProfesorForm()
    return render(request, 'cursos/agregar_profesor.html', {'form': form})

def editar_profesor(request, profesor_id):
    profesor = get_object_or_404(Profesor, pk=profesor_id)
    if request.method == 'POST':
        form = ProfesorForm(request.POST, instance=profesor)
        if form.is_valid():
            form.save()
            return redirect('lista_profesores')
    else:
        form = ProfesorForm(instance=profesor)
    return render(request, 'cursos/editar_profesor.html', {'form': form, 'profesor': profesor})

def eliminar_profesor(request, profesor_id):
    profesor = get_object_or_404(Profesor, pk=profesor_id)
    if request.method == 'POST':
        profesor.delete()
        return redirect('lista_profesores')
    return render(request, 'cursos/eliminar_profesor.html', {'profesor': profesor})

# Resto de vistas de Cursos -------------------------------------------

def lista_cursos(request):
    cursos = Curso.objects.all()
    return render(request, 'cursos/lista_cursos.html', {'cursos': cursos})

def agregar_curso(request):
    if request.method == 'POST':
        form = CursoForm(request.POST)
        if form.is_valid():
            curso = form.save(commit=False)
            form.save()
            return redirect('lista_cursos')
    else:
        form = CursoForm()
    return render(request, 'cursos/agregar_curso.html', {'form': form})

def editar_curso(request, curso_id):
    curso = get_object_or_404(Curso, pk=curso_id)
    if request.method == 'POST':
        form = CursoForm(request.POST, instance=curso)
        if form.is_valid():
            form.save()
            return redirect('lista_cursos')
    else:
        form = CursoForm(instance=curso)
    return render(request, 'cursos/editar_curso.html', {'form': form, 'curso': curso})

def eliminar_curso(request, curso_id):
    curso = get_object_or_404(Curso, pk=curso_id)
    if request.method == 'POST':
        curso.delete()
        return redirect('lista_cursos')
    return render(request, 'cursos/eliminar_curso.html', {'curso': curso})

# vistas de Lecciones ----------------------------------------

def lista_lecciones(request):
    lecciones = Leccion.objects.all()
    return render(request, 'cursos/lista_lecciones.html', {'lecciones': lecciones})

def agregar_leccion(request):
    if request.method == 'POST':
        form = LeccionForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('lista_lecciones')
    else:
        form = LeccionForm()
    return render(request, 'cursos/agregar_leccion.html', {'form': form})

def editar_leccion(request, leccion_id):
    leccion = get_object_or_404(Leccion, pk=leccion_id)
    if request.method == 'POST':
        form = LeccionForm(request.POST, instance=leccion)
        if form.is_valid():
            form.save()
            return redirect('lista_lecciones')
    else:
        form = LeccionForm(instance=leccion)
    return render(request, 'cursos/editar_leccion.html', {'form': form, 'leccion': leccion})

def eliminar_leccion(request, leccion_id):
    leccion = get_object_or_404(Leccion, pk=leccion_id)
    if request.method == 'POST':
        leccion.delete()
        return redirect('lista_lecciones')
    return render(request, 'cursos/eliminar_leccion.html', {'leccion': leccion})

# Vistas de Usuario

def registrar_usuario(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            return redirect('index')
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'registro_usuario.html', {'user_form': user_form, 'profile_form': profile_form})

def index(request):
    return render(request, 'cursos/index.html')

cursos/templates/cursos/agregar_curso.html
{% extends 'plantilla.html' %}

{% block content %}
<div class="container mt-4">
    <form method="post" enctype="multipart/form-data" class="p-4 bg-light">
        <h2>Agregar Curso</h2>
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_nombre" class="form-label">Nombre:</label>
            {{ form.nombre }}
        </div>
        <div class="mb-3">
            <label for="id_descripcion" class="form-label">Descripción:</label>
            {{ form.descripcion }}
        </div>
        <div class="mb-3">
            <label for="id_profesores" class="form-label">Profesores:</label>
            {{ form.profesores }}
        </div>
        <div class="mb-3">
            <label for="id_estudiantes" class="form-label">Estudiantes:</label>
            {{ form.estudiantes }}
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>
{% endblock %}

cursos/templates/cursos/agregar_estudiante.html
{% extends 'plantilla.html' %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <div class="form-container">
        <form method="post" enctype="multipart/form-data">
            <h2>Crear Estudiante</h2>
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_identificacion" class="form-label">Identificación</label>
                <input type="text" name="identificacion" class="form-control" id="id_identificacion" required>
            </div>
            <div class="mb-3">
                <label for="id_nombre" class="form-label">Nombre</label>
                <input type="text" name="nombre" class="form-control" id="id_nombre" required>
            </div>
            <div class="mb-3">
                <label for="id_apellido" class="form-label">Apellido</label>
                <input type="text" name="apellido" class="form-control" id="id_apellido" required>
            </div>
            <button type="submit" class="btn btn-primary">Crear Estudiante</button>
        </form>
    </div>
</div>
{% endblock %}

cursos/templates/cursos/agregar_leccion.html
{% extends 'plantilla.html' %}

{% block content %}
<div class="container mt-4">
    <form method="post" enctype="multipart/form-data" class="p-4 bg-light">
        <h2>Agregar Lección</h2>
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_nombre" class="form-label">Nombre:</label>
            {{ form.nombre }}
        </div>
        <div class="mb-3">
            <label for="id_curso" class="form-label">Curso:</label>
            {{ form.curso }}
        </div>
        <div class="mb-3">
            <label for="id_descripcion_actividad" class="form-label">Descripción de la Actividad:</label>
            {{ form.descripcion_actividad }}
        </div>
        <div class="mb-3">
            <label for="id_contenido" class="form-label">Contenido:</label>
            {{ form.contenido }}
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>
{% endblock %}

cursos/templates/cursos/agregar_profesor.html
{% extends 'plantilla.html' %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <div class="form-container">
        <form method="post" enctype="multipart/form-data">
            <h2>Crear Profesor</h2>
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_identificacion" class="form-label">Identificación</label>
                <input type="text" name="identificacion" class="form-control" id="id_identificacion" required>
            </div>
            <div class="mb-3">
                <label for="id_nombre" class="form-label">Nombre</label>
                <input type="text" name="nombre" class="form-control" id="id_nombre" required>
            </div>
            <div class="mb-3">
                <label for="id_apellido" class="form-label">Apellido</label>
                <input type="text" name="apellido" class="form-control" id="id_apellido" required>
            </div>
            <button type="submit" class="btn btn-primary">Crear Profesor</button>
        </form>
    </div>
</div>
{% endblock %}

cursos/templates/cursos/editar_curso.html
{% extends 'plantilla.html' %}

{% block content %}
<div class="container mt-4">
    <form method="post" enctype="multipart/form-data" class="p-4 bg-light" id="cursoForm">
        <h2>Editar Curso</h2>
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_nombre" class="form-label">Nombre:</label>
            {{ form.nombre }}
        </div>
        <div class="mb-3">
            <label for="id_descripcion" class="form-label">Descripción:</label>
            {{ form.descripcion }}
        </div>
        <div class="mb-3" id="profesoresContainer">
            <label for="id_profesores" class="form-label">Profesores:</label>
            {{ form.profesores }}
            <button type="button" class="btn btn-sm btn-secondary" onclick="agregarCampo('profesoresContainer', 'profesores')">Agregar Profesor</button>
        </div>
        <div class="mb-3" id="estudiantesContainer">
            <label for="id_estudiantes" class="form-label">Estudiantes:</label>
            {{ form.estudiantes }}
            <button type="button" class="btn btn-sm btn-secondary" onclick="agregarCampo('estudiantesContainer', 'estudiantes')">Agregar Estudiante</button>
        </div>
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
</div>

<script>
    function agregarCampo(containerId, fieldId) {
        const container = document.getElementById(containerId);
        const selectField = document.getElementsByName(fieldId)[0].cloneNode(true);
        container.appendChild(selectField);
    }
</script>
{% endblock %}

cursos/templates/cursos/editar_estudiante.html
{% extends 'plantilla.html' %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <div class="form-container">
        <form method="post" action="{% url 'editar_estudiante' estudiante_id=estudiante.identificacion %}" enctype="multipart/form-data">
            <h2>Editar Estudiante</h2>
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_identificacion" class="form-label">Identificación</label>
                <input type="text" name="identificacion" value="{{ estudiante.identificacion }}" class="form-control" id="id_identificacion" required>
            </div>
            <div class="mb-3">
                <label for="id_nombre" class="form-label">Nombre</label>
                <input type="text" name="nombre" value="{{ estudiante.nombre }}" class="form-control" id="id_nombre" required>
            </div>
            <div class="mb-3">
                <label for="id_apellido" class="form-label">Apellido</label>
                <input type="text" name="apellido" value="{{ estudiante.apellido }}" class="form-control" id="id_apellido" required>
            </div>
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </form>
    </div>
</div>
{% endblock %}

cursos/templates/cursos/editar_leccion.html
{% extends 'plantilla.html' %}

{% block content %}
<div class="container mt-4">
    <form method="post" enctype="multipart/form-data" class="p-4 bg-light">
        <h2>Editar Lección: {{ leccion.nombre }}</h2>
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_nombre" class="form-label">Nombre:</label>
            {{ form.nombre }}
        </div>
        <div class="mb-3">
            <label for="id_curso" class="form-label">Curso:</label>
            {{ form.curso }}
        </div>
        <div class="mb-3">
            <label for="id_descripcion_actividad" class="form-label">Descripción de la Actividad:</label>
            {{ form.descripcion_actividad }}
        </div>
        <div class="mb-3">
            <label for="id_contenido" class="form-label">Contenido:</label>
            {{ form.contenido }}
        </div>
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
</div>
{% endblock %}

cursos/templates/cursos/eliminar_profesor.html
{% extends 'plantilla.html' %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <div class="form-container">
        <h2>Eliminar Profesor</h2>
        <p>¿Estás seguro de que deseas eliminar este profesor?</p>
        <p><strong>Identificación:</strong> {{ profesor.identificacion }}</p>
        <p><strong>Nombre:</strong> {{ profesor.nombre }}</p>
        <p><strong>Apellido:</strong> {{ profesor.apellido }}</p>

        <form method="post" action="{% url 'eliminar_profesor' profesor_id=profesor.identificacion %}" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Eliminar</button>
        </form>
        <a href="{% url 'lista_profesores' %}" class="btn btn-secondary">Cancelar</a>
    </div>
</div>
{% endblock %}

cursos/templates/cursos/lista_estudiantes.html
{% extends 'plantilla.html' %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <h2 style="color: white;">Lista de Estudiantes</h2>
    <a href="{% url 'agregar_estudiante' %}" class="btn btn-primary mb-2">Agregar Estudiante</a>
    <br>
    <table class="table">
        <thead>
            <tr>
                <th>Identificación</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for estudiante in estudiantes %}
            <tr>
                <td>{{ estudiante.identificacion }}</td>
                <td>{{ estudiante.nombre }}</td>
                <td>{{ estudiante.apellido }}</td>
                <td>
                    <a href="{% url 'editar_estudiante' estudiante_id=estudiante.identificacion %}" class="btn btn-sm btn-info">Editar</a>
                    <a href="{% url 'eliminar_estudiante' estudiante_id=estudiante.identificacion %}" class="btn btn-sm btn-danger">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

cursos/templates/cursos/lista_lecciones.html
{% extends 'plantilla.html' %}

{% block content %}
<div class="mb-3">
    <a href="{% url 'agregar_leccion' %}" class="btn btn-success">Agregar Lección</a>
</div>
<div class="row">
    {% for leccion in lecciones %}
    <div class="col-md-4 mb-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ leccion.nombre }}</h5>
                <p class="card-text">{{ leccion.descripcion_actividad }}</p>
                <p class="card-text">Curso: {{ leccion.curso.nombre }}</p>
                <p class="card-text">
                    <a href="{{ leccion.contenido.url }}" target="_blank" class="btn btn-primary">Abrir Documento</a>
                </p>
                <div class="mt-3">
                    <a href="{% url 'editar_leccion' leccion_id=leccion.pk %}" class="btn btn-primary">Editar</a>
                    <form method="post" action="{% url 'eliminar_leccion' leccion_id=leccion.pk %}" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

cursos/templates/cursos/lista_profesores.html
{% extends 'plantilla.html' %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <h2 style="color: white;">Lista de Profesores</h2>
    <a href="{% url 'agregar_profesor' %}" class="btn btn-primary mb-2">Agregar Profesor</a>
    <br>
    <table class="table">
        <thead>
            <tr>
                <th>Identificación</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for profesor in profesores %}
            <tr>
                <td>{{ profesor.identificacion }}</td>
                <td>{{ profesor.nombre }}</td>
                <td>{{ profesor.apellido }}</td>
                <td>
                    <a href="{% url 'editar_profesor' profesor_id=profesor.identificacion %}" class="btn btn-sm btn-info">Editar</a>
                    <a href="{% url 'eliminar_profesor' profesor_id=profesor.identificacion %}" class="btn btn-sm btn-danger">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

cursos/templates/cursos/login.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar sesión</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'estilos.css' %}" rel="stylesheet">
</head>
<body id="login-body">

<main class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
          <form method="post" class="form-signin">
            <h2 class="mb-4 center-title">Iniciar sesión</h2>
            <h2 class="mb-4 center-title"></h2>
            {% csrf_token %}
            <div class="mb-3">
              <label for="username" class="form-label">Usuario</label>
              <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="mb-3">
              <label for="password" class="form-label">Contraseña</label>
              <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <div class="center-button">
              <button type="submit" class="btn btn-lg btn-primary btn-block">Iniciar sesión</button>
            </div>
          </form>
        </div>
      </div>
</main>

<!-- Bootstrap JS y dependencias -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</body>
</html>